package org.jacpower.enums;

public enum RequestTypes {
    CREATE_MERCHANT, CREATE_ADMIN, AUTHENTICATE_USER, CREATE_CUSTOMER, ADD_CATEGORY,
    ADD_PRODUCT, GET_ALL_PRODUCTS, ADD_TO_CART, REMOVE_FROM_CART, GET_CART_ITEMS, ADD_PAYMENT
}
